/**:
  ros__parameters:
    num_wheels: 4
    device: eno1
    base_frame_id: "base_footprint"

    vlin_max: 0.5  # m / s
    # va_max: 1.5  # rad / s
    # vlin_acc_max: 0.4  # m / s^2
    # vlin_dec_max: 1.0  # m / s^2
    # va_acc_max: 0.5  # rad / s^2
    # va_dec_max: 1.0  # rad / s^2

    
    #longer side of the kelo drive is back side
    # --- Working Translation and bit of rotation --- # Don't Touch
  
    wheel0:    #FL
      ethercat_number: 7
      # x: 0.210
      # y: -0.100
      x: 0.210
      y: 0.100
      a: 5.299999


    wheel1:    #BL
      ethercat_number: 2
      # x: 0.210
      # y: 0.100
      x: -0.210
      y: +0.100
      a: 4.687

    wheel2:   #BR
      ethercat_number: 4
      # x: -0.210
      # y: 0.100
      x: -0.210
      y: -0.100
      a: 2.389
      
    wheel3:  #FR
      ethercat_number: 6
      # x: -0.210
      x: +0.210
      # y: -0.100
      y: -0.100
      a: 1.630
     
     # --- Working Translation and a bit of rotation--- #

    #longer side of the kelo drive is back side
    # --- Working Translation and bit of rotation --- # Don't Touch
      
platform_driver:
  ros__parameters:
    modules:
      list: ["platform_driver"]
      platform_driver:
        type: platform_driver
        controller: velocity_platform_controller





    